### ISSUE TITLE
failed to build with xxhash-c-sys 0.8.3

### ISSUE THREAD

**Issue by sprhawk** [DoumanAsh/xxhash-c#2]
error[E0308]: mismatched types                                                                                                                                
   --> /home/hongbo/.cargo/registry/src/github.com-1ecc6299db9ec823/xxhash-c-0.8.1/src/lib.rs:145:37                                                          
    |                                                                                                                                                         
145 |         debug_assert!(self.len() >= xxhash_c_sys::XXH3_SECRET_SIZE_MIN);                                                                                
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `usize`, found `i32`

**Comment by DoumanAsh** [comment]
uff annoying, but it should be easy to fix

**Comment by DoumanAsh** [comment]
@sprhawk can you check there is no other compilation error with https://github.com/DoumanAsh/xxhash-c/commit/bce85218939423be3edd12e45caebbda2b4d7d31

**Comment by sprhawk** [comment]
> @sprhawk can you check there is no other compilation error with [bce8521](https://github.com/DoumanAsh/xxhash-c/commit/bce85218939423be3edd12e45caebbda2b4d7d31)

Use dep: ` xxhash-c = { git = "https://github.com/DoumanAsh/xxhash-c.git", rev = "bce8521" }`

build passed.

**Comment by DoumanAsh** [comment]
Thanks
Published 0.8.2
